FROM python:3.12

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get install -y git
RUN mkdir /code
WORKDIR /code

RUN git clone https://github.com/LMUK-RADONC-PHYS-RES/rt-rename.git
WORKDIR /code/rt-rename
CMD ["python", "app.py"]







