FROM python:3.12

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get install -y git
RUN mkdir /code
WORKDIR /code

RUN mkdir /code/rt-rename
WORKDIR /code/rt-rename








